### PR TITLE
Add statistics to JSON and YAML reports

### PR DESCRIPTION
**Pull request by egibs**
Addresses: #725

This is a first pass at adding statistics to JSON and YAML reports. For now, the values are not formatted or converted like the terminal-based statistics are.

JSON:
```
$ go run cmd/mal/mal.go --format json --stats --all analyze ~/Downloads/gitlab-rails/srv/gitlab/vendor/project_templates/iosswift.tar.gz | jq .Stats
{
  "RiskStats": [
    {
      "Count": 13,
      "Key": 0,
      "Total": 15,
      "Value": 86.66666666666667
    },
    {
      "Count": 1,
      "Key": 1,
      "Total": 15,
      "Value": 6.666666666666667
    },
    {
      "Count": 1,
      "Key": 2,
      "Total": 15,
      "Value": 6.666666666666667
    }
  ],
  "PkgStats": [
    {
      "Count": 1,
      "Key": "credential/password",
      "Total": 4,
      "Value": 25
    },
    {
      "Count": 1,
      "Key": "credential/sniffer/bpf",
      "Total": 4,
      "Value": 25
    },
    {
      "Count": 1,
      "Key": "net/tcp/ssh",
      "Total": 4,
      "Value": 25
    },
    {
      "Count": 1,
      "Key": "process/chdir",
      "Total": 4,
      "Value": 25
    }
  ],
  "TotalRisks": 15,
  "ProcessedFiles": 15,
  "SkippedFiles": 0,
  "TotalBehaviors": 4
}
```

YAML:
```
$ go run cmd/mal/mal.go --format yaml --stats --all analyze ~/Downloads/gitlab-rails/srv/gitlab/vendor/project_templates/iosswift.tar.gz | yq .stats
riskstats:
  - count: 13
    key: 0
    total: 15
    value: 86.66666666666667
  - count: 1
    key: 1
    total: 15
    value: 6.666666666666667
  - count: 1
    key: 2
    total: 15
    value: 6.666666666666667
pkgstats:
  - count: 1
    key: credential/password
    total: 4
    value: 25
  - count: 1
    key: credential/sniffer/bpf
    total: 4
    value: 25
  - count: 1
    key: net/tcp/ssh
    total: 4
    value: 25
  - count: 1
    key: process/chdir
    total: 4
    value: 25
totalrisks: 15
processedfiles: 15
skippedfiles: 0
totalbehaviors: 4
```

Also, when not using `--stats`, the `Stats` fields will not be present in the output.

### CODE REVIEW

**Comment by tstromberg** [comment]
Do you mind adding a test for this?

**Comment by egibs** [comment]
> Do you mind adding a test for this?

Added in [`ad5bc03` (#730)](https://github.com/chainguard-dev/malcontent/pull/730/commits/ad5bc038adba25462953a036b1d3e965984040d5).

**Review by stevebeattie — COMMENTED** [review]
This all looks good to me, except that when the diff option is passed, an empty Stats: dictionary is generated and appended, which differs from the terminal and strings renderers.

**Comment by egibs** [comment]
> This all looks good to me, except that when the diff option is passed, an empty Stats: dictionary is generated and appended, which differs from the terminal and strings renderers.

Ah, yea, that's an easy fix. I'll push that shortly.

**Comment by egibs** [comment]
> This all looks good to me, except that when the diff option is passed, an empty Stats: dictionary is generated and appended, which differs from the terminal and strings renderers.

Fixed in [`b080ad9` (#730)](https://github.com/chainguard-dev/malcontent/pull/730/commits/b080ad92065e8a145cdb00223acdb278dffbbb1f).

**Review by stevebeattie — APPROVED** [review]
Thanks for fixing that up, that works for me.

**Pull request merged**
