### PR TITLE
Improve detection of machO backdoors & stealers

### PR DESCRIPTION
**Pull request by tstromberg**
Based on studying some recent submissions to the Malware Bazaar.

### CODE REVIEW

**Comment by egibs** [comment]
It's odd that `make integration` doesn't seem to be completing with the changes in this branch. Generating the test data should indicate that the rules work and produce results but the tests never finishing is weird.

**Comment by tstromberg** [comment]
Yeah, it looks like there may be no fast way to match a long string of alphanumeric text. It turns out that compiled regexps are run across all files - not just the ones matching conditions:

https://github.com/Neo23x0/YARA-Performance-Guidelines

**Comment by tstromberg** [comment]
commit incoming to improve performance ...

**Comment by tstromberg** [comment]
updated rules are still slower than I like, but they are faster than they were.

there doesn't seem to be a fast way to detect a very large string with YARA :(

**Comment by tstromberg** [comment]
finished in 6 minutes - not bad! I had to remove a query, but the best improvement was adding a nul character up front to find the start character.

**Review by egibs — APPROVED** [review]

**Pull request merged**
